server:
  port: 8080

spring:
  application:
    name: franquicia-api
  data:
    mongodb:
      uri: mongodb://root:secret@localhost:27017/franquicia-db?authSource=admin&authMechanism=SCRAM-SHA-256
  main:
    web-application-type: reactive

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true

